server:
  http:
    addr: 0.0.0.0:40094
    timeout: 1s
  grpc:
    addr: 0.0.0.0:40095
    timeout: 1s
  websocket:
    addr: 0.0.0.0:40093
    timeout: 1s
    path: /
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
